### PR TITLE
Binary Search

### PR DESCRIPTION
**Pull request by Gautam-virmani**

### CODE REVIEW

**Comment by jsparmani** [comment]
Please add a `README.md` for the algorithm by following the template in file `ALGO_TEMPLATE_README`.

**Comment by Gautam-virmani** [comment]
I have updated the readme file as required.

**Comment by Gautam-virmani** [comment]
Hey I have added updated readme file merge it with main repository if there is no issue

**Comment by DakshKK** [comment]
This PR is being closed since your commits are on master, and it has clearly been stated that commits on master will be rejected.

Please follow [Contribution guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md).

**Pull request closed without merging**
