### PR TITLE
armstrong.js added

### PR DESCRIPTION
**Pull request by Yash7818**
armstrong program in javascript is added

### CODE REVIEW

**Comment by jsparmani** [comment]
Please add a `README.md` for the algorithm by following the template in file `ALGO_TEMPLATE_README`.

**Comment by Yash7818** [comment]
@jsparmani    a `readme.md` is already added into it named `armstrong.md` by someone. The logic described there is exactly same that of mine but implemented in javascript.

**Comment by DakshKK** [comment]
A **JS** file already exists, if you are implementing a new version of the algorithm, will keep this PR open, else please close it. If there are any changes you want to make or recommend, follow our [contribution guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md) while doing so.

An implementation in any other language is welcome.

**Comment by Yash7818** [comment]
@DakshKK but my program is more general than that of the added one. My program can work for any n digit number but the program present there is only acceptable for 3 digit number.

**Comment by DakshKK** [comment]
@Yash7818 then do this. Please modify the code in the existing file, or make a commit which deletes the file, and adds your one, so there will only be a single file, and there are no clashes.

If both files are to be kept, refer to the contribution guidelines, and name your file in an incremental order, that is `Armstrong2.js` so that I can merge your PR.

**Comment by Yash7818** [comment]
@DakshKK I will change the file name to armstrong2.js

**Comment by DakshKK** [comment]
Please do so.

**Pull request merged**
