### PR TITLE
added python algo to check if number is palindrome

### PR DESCRIPTION
**Pull request by MRaahulVignesh**

### CODE REVIEW

**Comment by DhairyaSethi** [comment]
why you @MRaahulVignesh  :(

**Comment by jsparmani** [comment]
Please add a `README.md` for the algorithm by following the template in file `ALGO_TEMPLATE_README`.

**Comment by MRaahulVignesh** [comment]
Hey @jsparmani, there is another PR containing the readme file for the same algorithm? Do you want me to create another one?

**Comment by DakshKK** [comment]
@MRaahulVignesh if there any changes to be made according to you in the `README.md`, please create an issue for it first. Else there is no need for that.

**Pull request merged**
