### PR TITLE
Added Sieve of Eratosthenes

### PR DESCRIPTION
**Pull request by nj1902**
# Hacktoberfest2020

### CODE REVIEW

**Comment by jsparmani** [comment]
Please add a `README.md` for the algorithm by following the template in file `ALGO_TEMPLATE_README`.

**Comment by nj1902** [comment]
I have synchronized README with asked format and added python code as well.

**Comment by DakshKK** [comment]
Follow [contribution guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md) and refer the issue this is tackling.

Add a description in your PR of the changes made. But a good implementation.

**Comment by DakshKK** [comment]
Also this PR is being closed, since it was clearly stated that no PRs on master branch will be entertained.

Branch your git workflow, and make your commits there. Once done, please re-open a new PR, following our [Contribution Guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md).

**Pull request closed without merging**
