### PR TITLE
Added Palindrome

### PR DESCRIPTION
**Pull request by Abtaha**
Added C++ file which checks whether an input (positive integer) is a palindrome or not. 
README also added

Issue #59

### CODE REVIEW

**Comment by DakshKK** [comment]
Looks good. Can you try and implement it in a few more languages.
Would recommend the following
1. Python
1. JavaScript
1. Java

**Comment by Abtaha** [comment]
Done

**Comment by Abtaha** [comment]
Added C++, Javascript and Java files which check whether an input (positive integer) is a palindrome or not.

Issue #59

**Comment by DakshKK** [comment]
@Abtaha you still have commits which affect the markdown file.

Remove those commits, and make any changes you want in a separate PR.

**Pull request merged**
