### PR TITLE
Armstrong Number C++ and python code added

### PR DESCRIPTION
**Pull request by dragonman164**
C++ and Python Code added , Read me file added

### CODE REVIEW

**Comment by pranavvidyarthi7** [comment]
@dragonman164 tag the issue for which you have made the PR and write the name of the algo in the title of the PR too

**Comment by dragonman164** [comment]
I am not able to tag the issue with it. Can you help?

**Comment by pranavvidyarthi7** [comment]
just add this line in comments
fixes # 
this will open a popup choose from there it will automatically link it

**Comment by dragonman164** [comment]
ok

**Comment by dragonman164** [comment]
fixes #58

**Pull request merged**
